GCP_CLIENT_ID = "769057565071-6pg24v8iusmtgbdd9lugjftg6csdpind.apps.googleusercontent.com"
GCP_CLIENT_SECRET = "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"

[db_credentials]
host = "192.168.16.2\\INNOGENBC"
user = "rx_access"
password = "rx_@cc3ss"
rxtracking_database = "RXTracking"
innogen_database = "InnogenBC174"